# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "next" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: prod
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        if: ${{ env.RN_NPM_WRITE_TOKEN == '' }}
        run: |
          echo "echo the secret \"RN_NPM_WRITE_TOKEN\" has not been made; echo please go to \"settings \> secrets \> actions\" to create it"
        env:
          NPM_TOKEN: ${{ secrets.RN_NPM_WRITE_TOKEN }}
      - name: Run a multi-line script1
        if: ${{ env.RN_NPM_WRITE_TOKEN1 == '' }}
        run: |
          echo "echo the secret \"RN_NPM_WRITE_TOKEN1\" has not been made; echo please go to \"settings \> secrets \> actions\" to create it"
        env:
          NPM_TOKEN1: ${{ secrets.RN_NPM_WRITE_TOKEN1 }}

